name: todoey_flutter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  animated_text_kit: ^4.3.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_analytics: ^12.0.4
  flutter_progress_hud: ^2.0.2
  cloud_firestore: ^6.1.0
  geolocator: ^14.0.2
  baseflow_plugin_template: ^2.2.0
  http: ^1.6.0
  flutter_spinkit: ^5.2.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
